### ISSUE TITLE
Interactive mode should use print_message function

### ISSUE THREAD

**Issue by bogdan3d** [bogdan3d/apathetic-python#1]
@pieguy1327 create new branch to update interactive mode to use `print_message` function:
https://github.com/bogdan3d/apathetic-python/blob/master/new_world_order.py#L38-L39

Create pull request for this change.

Branch names should be in this format:
`<type_of_branch>/<issue_number>-<name_of_branch>`

Where "type_of_branch" is `feature` or `bug` for now.

This branch name will probably be:
`feature/1-interactive-mode-use-print-message`

**Comment by bogdan3d** [comment]
@pieguy1327 reverted your merge.

**Comment by bogdan3d** [comment]
Process should be branch -> code -> review -> test -> merge.

Your commit didn't use the function `print_message` - you just made `print` look more like a function.
What you're looking to do is just update that one line under the `# TODO` so that instead of `print message_input` it calls the function like this:

`print_message(message_input)`

Then remove the `# TODO` comment.

**Comment by pieguy1327** [comment]
O  I see now the #Todo is the actual thing to do Got it and will fix it.

**Comment by bogdan3d** [comment]
Yea, create the pull request and let me review it.

**Comment by pieguy1327** [comment]
Also didnt read what you had put before. sorry for my insolence I will flog myself and repent

**Comment by bogdan3d** [comment]
S'all good. So let's update our process to include a lot more interaction in the issue discussion. When your pull request is ready just add a comment to the issue with a link to the PR - like this:
#4 (just type # into the comments here and git will autocomplete with a list of pull requests)

**Comment by bogdan3d** [comment]
Looks good, merged. Only feedback would be commit messages that make sense and conforming to the branch names. This is because the history looks like this now:
```
bogdan@Bogdans-MacBook-Pro:~/dev/bogdan3d/apathetic-python$ git log --oneline
91f18c0 Merge pull request #4 from bogdan3d/real-edit
157d510 Changed the line
99ecbce Merge pull request #3 from bogdan3d/revert-2-This-is-totally-cooler-than-hello-world
```

"Changed the line" doesn't really mean anything - a better commit message would be something like "Updating to use print_message function in interactive mode" or "Using print_message function".

Additionally let's prefix the commit message with the issue number. So an ideal commit message would be:
> #1 Updating interactive mode to use print_message function.

**Comment by pieguy1327** [comment]
Wow thats pretty awesome. Seems like a pretty legit service. Yeah thought we was fucking around a little to much i guess Ill be more professional in the future must make bad dudes proud.

**Comment by pieguy1327** [comment]
Cool also didnt know I couldnt use the prefix in the comments thanks for pointing that out.

**Comment by bogdan3d** [comment]
Yea prefixing the commits just makes it easier to find which issue you were working on without having to do git blames or annotations. Makes figuring out why some random line of code was put in - kind of hard when there's hundreds of commits and thousands of line.

Your first ticket successfully resolved - congratulations!

**Comment by pieguy1327** [comment]
Thanks lol. Gonna get this shit down
