### ISSUE TITLE
Update iterations variable to pull from command line args

### ISSUE THREAD

**Issue by bogdan3d** [bogdan3d/apathetic-python#5]
Add another argument to argparse called "iterations" which should default to 1 and set the iterations value.

So the expected output would be something like this:
```
python new_world_order.py --message test --iterations 3
test
test
test
```

**Comment by pieguy1327** [comment]
I'll get to work on this tomorrow I gota turn in 6am gym tomorrow

**Comment by bogdan3d** [comment]
No rush dude. Just making issues so your queue isn't empty.

**Comment by pieguy1327** [comment]
Not to sure if im doing #5 right but gave it a good try.

**Comment by bogdan3d** [comment]
Code was good but you committed to master and created a merge request into a new branch.

Changes should occur in new branch and have a merge request done into master.

Reverted the commit to master.

Check which branch you're on in your editor or through the command line:
```
$ git branch
* master
  update/5-Adding-iterations-argument
```

...or using git status:
```
$ git status
On branch master
Your branch is up-to-date with 'origin/master'.
[...]
```

Other than commit being in wrong place everything else was fine - just redo in branch, create merge request to merge branch into master, and that'll be good to go.

**Comment by pieguy1327** [comment]
Yeah thats my bad Im not sure how I got switch to the master. Ill be more careful in the future.
